language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_API_LEVEL=26
    - ANDROID_BUILD_TOOLS_VERSION=26.0.0
android:
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  components:
    - tools
    - tools
    - platform-tools
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - build-tools-25.0.0
    - android-26
    - sys-img-armeabi-v7a-android-26


before_install:
  - yes | sdkmanager "platforms;android-26"
  - pip install --user codecov

before_script:
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &


script:
  - ./gradlew build check
  - ./gradlew testDebugUnitTest jacocoTestReport


after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codecov
